package com;

//This file is made by Lalit
import com.employee.EmpFrame;
import com.admin.AdminFrame;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Lalit
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainF
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        dp = new javax.swing.JDesktopPane();
        selectionIF = new javax.swing.JInternalFrame();
        selectionPanel = new javax.swing.JPanel();
        btnEmp = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        adminLoginIF = new javax.swing.JInternalFrame();
        adminPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        txtAdminPass = new javax.swing.JPasswordField();
        btnAdminBack = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        empLoginIF = new javax.swing.JInternalFrame();
        empPanel = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        txtEmpUsername = new javax.swing.JTextField();
        txtEmpPass = new javax.swing.JPasswordField();
        btnEmpBack = new javax.swing.JButton();
        btnEmpLogin = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width/4 , java.awt.Toolkit.getDefaultToolkit().getScreenSize().height/4);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectionIF.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        selectionIF.setToolTipText("");
        selectionIF.setVisible(true);

        selectionPanel.setBackground(new java.awt.Color(255, 99, 71));

        btnEmp.setBackground(new java.awt.Color(255, 204, 204));
        btnEmp.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        btnEmp.setForeground(new java.awt.Color(255, 99, 71));
        btnEmp.setText("Worker");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(255, 204, 204));
        btnAdmin.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 99, 71));
        btnAdmin.setText("Admin");
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        txtWelcome.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcome.setText("Welcome to the XXXXXXXX Portal");

        javax.swing.GroupLayout selectionPanelLayout = new javax.swing.GroupLayout(selectionPanel);
        selectionPanel.setLayout(selectionPanelLayout);
        selectionPanelLayout.setHorizontalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(txtWelcome))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectionPanelLayout.setVerticalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txtWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout selectionIFLayout = new javax.swing.GroupLayout(selectionIF.getContentPane());
        selectionIF.getContentPane().setLayout(selectionIFLayout);
        selectionIFLayout.setHorizontalGroup(
            selectionIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectionIFLayout.setVerticalGroup(
            selectionIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dp.add(selectionIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        adminLoginIF.setTitle("Admin Login");
        adminLoginIF.setPreferredSize(new java.awt.Dimension(960, 540));
        adminLoginIF.setVisible(false);

        adminPanel.setBackground(new java.awt.Color(0, 255, 51));

        lblTitle.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Admin Login Portal");

        lblUsername.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");

        txtAdminUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAdminUsername.setAutoscrolls(false);
        txtAdminUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAdminPass.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtAdminPass.setToolTipText("type password here");
        txtAdminPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAdminPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminPassKeyPressed(evt);
            }
        });

        btnAdminBack.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnAdminBack.setForeground(new java.awt.Color(0, 255, 51));
        btnAdminBack.setText("Back");
        btnAdminBack.setPreferredSize(new java.awt.Dimension(200, 100));
        btnAdminBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminBackActionPerformed(evt);
            }
        });

        btnAdminLogin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnAdminLogin.setForeground(new java.awt.Color(0, 255, 51));
        btnAdminLogin.setText("Login");
        btnAdminLogin.setPreferredSize(new java.awt.Dimension(200, 100));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lblTitle))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(btnAdminBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword))
                                .addGap(41, 41, 41)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdminUsername)
                                    .addComponent(txtAdminPass, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblUsername))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout adminLoginIFLayout = new javax.swing.GroupLayout(adminLoginIF.getContentPane());
        adminLoginIF.getContentPane().setLayout(adminLoginIFLayout);
        adminLoginIFLayout.setHorizontalGroup(
            adminLoginIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminLoginIFLayout.setVerticalGroup(
            adminLoginIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dp.add(adminLoginIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        empLoginIF.setTitle("Employee Login");
        empLoginIF.setPreferredSize(new java.awt.Dimension(960, 540));
        empLoginIF.setVisible(false);

        empPanel.setBackground(new java.awt.Color(0, 204, 255));

        lblTitle1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Employee Login Portal");

        lblUsername1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username");

        lblPassword1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Password");

        txtEmpUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtEmpUsername.setAutoscrolls(false);
        txtEmpUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtEmpPass.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtEmpPass.setToolTipText("type password here");
        txtEmpPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmpPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpPassKeyPressed(evt);
            }
        });

        btnEmpBack.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnEmpBack.setForeground(new java.awt.Color(51, 153, 255));
        btnEmpBack.setText("Back");
        btnEmpBack.setPreferredSize(new java.awt.Dimension(200, 100));
        btnEmpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpBackActionPerformed(evt);
            }
        });

        btnEmpLogin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnEmpLogin.setForeground(new java.awt.Color(51, 153, 255));
        btnEmpLogin.setText("Login");
        btnEmpLogin.setPreferredSize(new java.awt.Dimension(200, 100));
        btnEmpLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empPanelLayout = new javax.swing.GroupLayout(empPanel);
        empPanel.setLayout(empPanelLayout);
        empPanelLayout.setHorizontalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(lblTitle1)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addComponent(btnEmpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnEmpBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername1)
                            .addComponent(lblPassword1))
                        .addGap(41, 41, 41)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmpUsername)
                            .addComponent(txtEmpPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(251, 251, 251))
        );
        empPanelLayout.setVerticalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle1)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblUsername1))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtEmpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword1)
                    .addComponent(txtEmpPass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout empLoginIFLayout = new javax.swing.GroupLayout(empLoginIF.getContentPane());
        empLoginIF.getContentPane().setLayout(empLoginIFLayout);
        empLoginIFLayout.setHorizontalGroup(
            empLoginIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        empLoginIFLayout.setVerticalGroup(
            empLoginIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dp.add(empLoginIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:        
        selectionIF.setVisible(false);
        adminLoginIF.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnAdminBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminBackActionPerformed
        // TODO add your handling code here:
        adminLoginIF.setVisible(false);
        selectionIF.setVisible(true);
    }//GEN-LAST:event_btnAdminBackActionPerformed

    private void checkAdminLogin() {
        String uname = txtAdminUsername.getText().trim();
        String pass = txtAdminPass.getText().trim();

        Connection conn = null;
        Postgre p = new Postgre();

        try {
            conn = p.connectDB();

            String sql = "select * from adminlogin where username=? and passw=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, uname);
            ps.setString(2, pass);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login Sucessfull!");
                AdminFrame adf = new AdminFrame(conn, uname);
                adf.setVisible(true);
                adf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "invalid login details", "Error Window", WARNING_MESSAGE);
                p.closeConn(conn, null, null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error Window", ERROR_MESSAGE);
            //e.printStackTrace();
        }
    }

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        checkAdminLogin();
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    public void openAdminLogin() {
        selectionIF.setVisible(false);
        adminLoginIF.setVisible(true);
    }

    public void openEmpLogin() {
        selectionIF.setVisible(false);
        empLoginIF.setVisible(true);
    }

    private void btnEmpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpBackActionPerformed
        // TODO add your handling code here:
        empLoginIF.setVisible(false);
        selectionIF.setVisible(true);
    }//GEN-LAST:event_btnEmpBackActionPerformed

    private void checkEmpLogin() {
        String uname = txtEmpUsername.getText().trim();
        String pass = txtEmpPass.getText().trim();

        Connection conn = null;
        Postgre p = new Postgre();

        try {
            conn = p.connectDB();
            String sql = "select * from emplogin where username=? and passw=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, uname);
            ps.setString(2, pass);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                EmpFrame adf = new EmpFrame(conn, uname);
                JOptionPane.showMessageDialog(this, "Login Sucessfull!");
                adf.setVisible(true);
                adf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "invalid login details", "Error Window", WARNING_MESSAGE);
                p.closeConn(conn, null, null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error Window", ERROR_MESSAGE);
            //e.printStackTrace();
        } finally {
            p.closeConn(conn, null, null);
        }

    }

    private void btnEmpLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpLoginActionPerformed
        // TODO add your handling code here:
        checkEmpLogin();
    }//GEN-LAST:event_btnEmpLoginActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        // TODO add your handling code here:
        selectionIF.setVisible(false);
        empLoginIF.setVisible(true);
    }//GEN-LAST:event_btnEmpActionPerformed

    private void txtAdminPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            checkAdminLogin();
        }
    }//GEN-LAST:event_txtAdminPassKeyPressed

    private void txtEmpPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            checkEmpLogin();
        }
    }//GEN-LAST:event_txtEmpPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame adminLoginIF;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAdminBack;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnEmpBack;
    private javax.swing.JButton btnEmpLogin;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JInternalFrame empLoginIF;
    private javax.swing.JPanel empPanel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JInternalFrame selectionIF;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JTextField txtAdminUsername;
    private javax.swing.JPasswordField txtEmpPass;
    private javax.swing.JTextField txtEmpUsername;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
