package com.admin;


import com.Postgre;
import com.MainFrame;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author a
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    String username;
    Connection conn;

    public AdminFrame(Connection x, String username) {
        initComponents();
        this.username = username;
        this.conn = x;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        dp = new javax.swing.JDesktopPane();
        adminMenuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        changePassw = new javax.swing.JMenuItem();
        viewProfile = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        employees = new javax.swing.JMenuItem();
        categoies = new javax.swing.JMenuItem();
        products = new javax.swing.JMenuItem();
        menuManage1 = new javax.swing.JMenu();
        generateSale = new javax.swing.JMenuItem();
        viewSales = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        menuMenu.setForeground(new java.awt.Color(0, 0, 0));
        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        changePassw.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        changePassw.setText("CHANGE PASSWORD");
        changePassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswActionPerformed(evt);
            }
        });
        menuMenu.add(changePassw);

        viewProfile.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        viewProfile.setText("VIEW PROFILE");
        viewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileActionPerformed(evt);
            }
        });
        menuMenu.add(viewProfile);

        logout.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menuMenu.add(logout);

        exit.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menuMenu.add(exit);

        adminMenuBar.add(menuMenu);

        menuManage.setForeground(new java.awt.Color(0, 0, 0));
        menuManage.setText("Manage");
        menuManage.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        employees.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        employees.setText("EMPLOYEES");
        employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesActionPerformed(evt);
            }
        });
        menuManage.add(employees);

        categoies.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        categoies.setText("CATEGORIES");
        categoies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoiesActionPerformed(evt);
            }
        });
        menuManage.add(categoies);

        products.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        products.setText("PRODUCTS");
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        menuManage.add(products);

        adminMenuBar.add(menuManage);

        menuManage1.setForeground(new java.awt.Color(0, 0, 0));
        menuManage1.setText("Sales");
        menuManage1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        generateSale.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        generateSale.setText("Generate Sale");
        generateSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSaleActionPerformed(evt);
            }
        });
        menuManage1.add(generateSale);

        viewSales.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        viewSales.setText("View Sales");
        viewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesActionPerformed(evt);
            }
        });
        menuManage1.add(viewSales);

        adminMenuBar.add(menuManage1);

        setJMenuBar(adminMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        try {
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error Window", ERROR_MESSAGE);
        }

        this.dispose();
        
        MainFrame obj = new MainFrame();
        obj.setVisible(true);
        obj.openAdminLogin();

    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void changePasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswActionPerformed

        ChangeAdminPassw e = new ChangeAdminPassw(conn, username);
        e.setVisible(true);        
        dp.add(e);

    }//GEN-LAST:event_changePasswActionPerformed

    private void categoiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoiesActionPerformed
        Categories e = new Categories(conn, username);
        e.setVisible(true);
        dp.add(e);
    }//GEN-LAST:event_categoiesActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        Products e = new Products(conn, username);
        e.setVisible(true);
        dp.add(e);
    }//GEN-LAST:event_productsActionPerformed

    
    private void employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesActionPerformed
        EmployeeIF e = new EmployeeIF(conn, username);
        e.setVisible(true);        
        dp.add(e);
    }//GEN-LAST:event_employeesActionPerformed

    private void viewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileActionPerformed
        // TODO add your handling code here:
        AdminProfile ap = new AdminProfile(conn, username);
        ap.setVisible(true);
        dp.add(ap);        
    }//GEN-LAST:event_viewProfileActionPerformed

    private void generateSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSaleActionPerformed
        // TODO add your handling code here:
        AdminSalesIF asi = new AdminSalesIF(conn, username);
        asi.setVisible(true);
        dp.add(asi);
    }//GEN-LAST:event_generateSaleActionPerformed

    private void viewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesActionPerformed
        // TODO add your handling code here:
        ViewSalesIF vs = new ViewSalesIF(conn, username);
        vs.setVisible(true);
        dp.add(vs);
    }//GEN-LAST:event_viewSalesActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String[] args) {
        Connection conn = new Postgre().connectDB();
        AdminFrame af = new AdminFrame(conn, "ls9");
        af.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar adminMenuBar;
    private javax.swing.JMenuItem categoies;
    private javax.swing.JMenuItem changePassw;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenuItem employees;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem generateSale;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenu menuManage1;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem products;
    private javax.swing.JMenuItem viewProfile;
    private javax.swing.JMenuItem viewSales;
    // End of variables declaration//GEN-END:variables
}
