package com.admin;

//This file is made by Lalit


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lalit
 */
public class ChangeAdminPassw extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePassw
     */
    Connection conn;
    String username;

    public ChangeAdminPassw(Connection c, String uname) {
        this.conn = c;
        this.username = uname;
        initComponents();
        setPosition();         
     }
    
    private void setPosition(){        
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension screen = new Dimension(t.getScreenSize());
        Dimension currentWindow = this.getBounds().getSize();
        int y = ((screen.height - currentWindow.height)/2)-20;
        int x = (screen.width - currentWindow.width)/2;
        this.setLocation(x, y);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpanel = new javax.swing.JPanel();
        txtConfirmPassw = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblUsername2 = new javax.swing.JLabel();
        txtOldPassw = new javax.swing.JPasswordField();
        txtNewPassw = new javax.swing.JPasswordField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Change Password");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        cpanel.setBackground(new java.awt.Color(0, 204, 102));
        cpanel.setPreferredSize(new java.awt.Dimension(900, 700));
        cpanel.setRequestFocusEnabled(false);
        cpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConfirmPassw.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtConfirmPassw.setToolTipText("type password here");
        txtConfirmPassw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpanel.add(txtConfirmPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 300, 55));

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("New Password");
        cpanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        lblUsername.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Change Password Portal");
        cpanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lblUsername1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Confirm Password");
        cpanel.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        btnChange.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnChange.setForeground(new java.awt.Color(0, 204, 102));
        btnChange.setText("Change");
        btnChange.setPreferredSize(new java.awt.Dimension(200, 100));
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        cpanel.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, 80));

        btnCancel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 204, 102));
        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(200, 100));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        cpanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, 80));

        lblUsername2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername2.setText("Old Password");
        cpanel.add(lblUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        txtOldPassw.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtOldPassw.setToolTipText("type password here");
        txtOldPassw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpanel.add(txtOldPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 300, 55));

        txtNewPassw.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtNewPassw.setToolTipText("type password here");
        txtNewPassw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpanel.add(txtNewPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 300, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        String oldPassw = txtOldPassw.getText().trim();
        String newPassw = txtNewPassw.getText().trim();
        String confirmPassw = txtConfirmPassw.getText().trim();

        String sql = "";
        PreparedStatement ps;
        ResultSet rs;

        try {

            if (newPassw.equals(confirmPassw)) {
                sql = "select passw from adminlogin where username=?";
                ps = conn.prepareStatement(sql);
                ps.setString(1, username);
                rs = ps.executeQuery();

                String oldp = "";
                if (rs.next()) {
                    oldp = rs.getString("passw");
                }

                if (oldp.equals(oldPassw)) {
                    sql = "update adminlogin set passw=? where username=?";
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, newPassw);
                    ps.setString(2, username);

                    int count = ps.executeUpdate();

                    if (count > 0) {
                        JOptionPane.showMessageDialog(this, count + "password changed !!!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Old Password does not matched!!!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "New password & Confirm Password does not matched!!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JPanel cpanel;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPasswordField txtConfirmPassw;
    private javax.swing.JPasswordField txtNewPassw;
    private javax.swing.JPasswordField txtOldPassw;
    // End of variables declaration//GEN-END:variables
}
