package com.admin;

//This file is made by Lalit
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lalit
 */
public class ViewSalesIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeIF
     */
    Connection conn;
    String username;

    public ViewSalesIF(Connection c, String uname) {
        this.conn = c;
        this.username = uname;
        initComponents();
        this.showAllSales();
    }
    
    /*
    void clearForm() {
        txthiredate.setDate(null);
        txtdob.setDate(null);
        txtUsername.setText("");
        txtfname.setText("");
        txtlname.setText("");
        txtage.setText("");
        txtcontact.setText("");
        txtemail.setText("");
        txtaddress.setText("");
        txtpincode.setText("");
        txtcity.setText("");
        txtstate.setText("");
        txtcountry.setText("");
    }
*/
    
    void showAllSales() {
        String sql = "select sale_id,product_id, product_price, quantity, total_price, discount, tax, final_amount, customer_fname, customer_lname, customer_contactno,  customer_email,  customer_address,  customer_city,  customer_state,  customer_country from sales";
        Vector heading = new Vector();
        heading.add("sale_id");
        heading.add("product_id");
        heading.add("Price");
        heading.add("Quantity");
        heading.add("total_price");
        heading.add("discount");
        heading.add("tax");
        heading.add("final_amount");
        heading.add("Full Name");
        heading.add("Contact");
        heading.add("Email");
        heading.add("Address");
        heading.add("City");
        heading.add("State");
        heading.add("Country");

        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            Vector data = new Vector();
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("sale_id"));
                row.add(rs.getString("product_id"));
                row.add(rs.getString("product_price"));
                row.add(rs.getString("quantity"));
                row.add(rs.getString("total_price"));
                row.add(rs.getString("discount"));
                row.add(rs.getString("tax"));
                row.add(rs.getString("final_amount"));
                row.add(rs.getString("customer_fname") + " " + rs.getString("customer_lname"));
                row.add(rs.getString("customer_contactno"));
                row.add(rs.getString("customer_email"));
                row.add(rs.getString("customer_address"));
                row.add(rs.getString("customer_city"));
                row.add(rs.getString("customer_state"));
                row.add(rs.getString("customer_country"));

                data.add(row);
            }

            DefaultTableModel tm = new DefaultTableModel(data, heading);
            salesTbl.setModel(tm);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpGender = new javax.swing.ButtonGroup();
        jtab = new javax.swing.JTabbedPane();
        saleTbl = new javax.swing.JScrollPane();
        salesTbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1500, 900));

        jtab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        saleTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        salesTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        salesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesTbl.setRowHeight(22);
        salesTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTblMouseClicked(evt);
            }
        });
        saleTbl.setViewportView(salesTbl);

        jtab.addTab("Table", saleTbl);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1488, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );

        jtab.addTab("Details", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String initialUsername;
    private void salesTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTblMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_salesTblMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpGender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JScrollPane saleTbl;
    private javax.swing.JTable salesTbl;
    // End of variables declaration//GEN-END:variables
}
